x-restart-policy: &restart_policy
  # our policy is always restart the container unless it is explicitly stopped
  # or Docker daemon is restarted
  restart: unless-stopped
services:
  api:
    build:
      context: .
      target: base
      args:
        - NODE_ENV=local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
    env_file:
      - .env-example
    depends_on:
      - postgres

  postgres:
    <<: *restart_policy
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env-example
