x-restart-policy: &restart_policy
  # our policy is always restart the container unless it is explicitly stopped
  # or Docker daemon is restarted
  restart: unless-stopped
services:
  database-test:
    <<: *restart_policy
    image: "postgres:15-alpine"
    ports:
      - "5433:5432"
    env_file: ".env.test"
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s

  redis-test:
    <<: *restart_policy
    image: "redis:7-alpine"
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s

  wait:
    image: hello-world:latest
    depends_on:
      database-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
