version: "3.8"

x-restart-policy: &restart_policy
  # our policy is always restart the container unless it is explicitly stopped
  # or Docker daemon is restarted
  restart: unless-stopped
services:
  api:
    build:
      context: .
      target: base
      args:
        - NODE_ENV=local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=local
    env_file:
      - .env
    depends_on:
      database:
        condition: service_healthy
        restart: true

  database:
    <<: *restart_policy
    image: "postgres:15-alpine"
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 15s
